language: java
sudo: false
jdk:
- oraclejdk8
- oraclejdk9
- openjdk8
before_install:
- chmod +x gradlew
script: "./gradlew junitPlatformTest"
stages:
- test
- coverage
- name: snapshot
  if: branch != master
- name: release
  if: branch = master
jobs:
  include:
  - stage: coverage
    script:
    - "./gradlew check"
    - bash <(curl -s https://codecov.io/bash)
    jdk: oraclejdk8
  - stage: snapshot
    script: "./gradlew artifactoryPublish -Dsnapshot=true -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER"
    jdk: oraclejdk8
  - stage: release
    script: "./gradlew bintrayUpload -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dsigning.pass=$SIGN_PASS -Dbuild.number=$TRAVIS_BUILD_NUMBER"
    jdk: oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/repositories/"
env:
  global:
  - secure: x0f5zMalbU3zNxoeqEdNMCeIvuIfxIbD7MzuS/1QXXnNGm8WkuyIttLB2y7eW/eQX89ZfZek/sy3+/M9N87EdOBbghaex3WbD1V/cE6fEy3u05FiKpn7gIYUXejBdz/9Ez2a6LO3Axr1XWAQRL5sxSjyATKLRP+muV5igcFUXjwFeHW4Lv9TLUj3dR1g6gVo0NDTwjrrNwyQkhH3J+7+wdq27KbOGCLL0IkR/RicEGLU3kGwl7sgxFw8WlanIJDNmVKzgRoJQC/4PKHQ5oqVEtkaXDJKSp+rwSGroSrEmDEutCp+dme1l+TM0UD5Wq/jf0QC/jnr3ZYx0t3mztiTt71m9PA5f0U9TNX/H4TVNX7q7tsyUHC6v6c/n7KAV73ZgWFQiPzhevbpPl8V+MCH3eTPww30DyKV858E2wcoEJkSRZruCekYfHOG16JvKY8E0XHUTsqfHMIAc96f+0H5/om9QmX6jTJEvUUXmW0QdtoKHo6jBjdDFriihX0KVYW7NS5juRbdUOnWXIFOfhsNUDMNHxVik0t6ZN7pZDCxSVZINBPBWPZjlItzsYLJLEwF/IP/wHEH1Bqz9rY7Z5s7z96AUIPVT/97GGJZnFywlDzXpjOGMnRchZROgDGo0wbvyb+KlDFWlYR4kJ2mTxJXCYRilpfw4ImyzM59WuhwOWU=
  - secure: U51k2EQKUL3wPAggUM5vSfhXFMzgxlbEaQHwdgxvA8p5nmwDryuI2HWZCydryJ62ZfhD8auQy5hxqJPHEY0qMdEAjZwMoQbXHwpeiiH7RRP6N//l3IBDnCCB/a4/C046+XFMu7ar/yueZ5UIPsy615OqSclITekKOstNIQpHlqgNO8YfSK9zw5P067G1IvX6xgq6VywYkQIxq3v92cBFbKZnR/+87+h8gnofT8eRXpToMAW9aCzDUY/sjkUx3ID+ntZOme/1Jf3uNJA/cmCjAVoSqRnFEVLnhPxfRyjbO6ZymViMGsvXn3oclm4v8Pno6ABHk4BtwlwdsjpQRIBCZqvKaUuVy0dZ5Wkqf+oD/tD7mn9z/u1p/v+AEjHhqNZeDqRWWdadBjeC5QWZRljKyduBMiqRqF8yt8sWDKMhK+JZh6gGxI0gqPJSgNPD1WbXFfiQ1q/+d7Y257Y6jx6SrPKfyXPyTHJKyLP0SZUNfuIdN35uVRDihJjJuCSz68yiJCVu2Rv769UZx7WJoOJLRGsWOqrZcS735kJ7XFBgzbvjyw7K8Xbz0mdrQJz0AsXfZvegH4HrkyXEf50At4RZHoRUTlWvTjQGfQwv3l3iWFTNXFxORwP/mVrMGqBTq+oV15VlkZELumhJLTm8w1w9O+hobje58GqAhXswYT/UHaw=
  - secure: Zth+veRj8nXVQGk8v/RyyoPjk1/lZ1hex3M/p2bhPJcwGO4qkq+hDcRCHx8a95Af/fpX5yhgsT2WN1lu0ieIbf0kDC5a55xe60EiPDS1bTn87Jdc1AYwczEfko36OaH+SR1/ropLBfXIBWzbuyo8ffp1nft0RXJjP02hcZcZxJCezQR47MVMs9SfRwCP4xsASAuhs5QhVRKIuOT4J1e1IsnktzjBI1M4dlr3+wNhicLLhCBAB6rfADS0iu1d81f2cZLw5+vADuw5DpWmULM8idB7oQlzQqf4dBXK4yEGlx8LMjyHbNGuXCBGl3+/0jcoDYq2U5QxY7+SDSfGzCscGsjqGBrimmM1OEyuEAcwNel3s+Wydfe0M8hiRc7+SMYjze/q+Ao/EJMHHtUZs4XmbDTnuZQtnEb5MSXKriMCDZlnCHLl8D9xrJPoQbdok9r4EBAP3cZtG1m+lNZYUU9wTMhlpcXVMSZH9rzbLvqzeFIynor45I9clWIkNMWu9Z2vLHCslw76mebt3eYiIYMlEBbKuT+wf7vgOqvKhRph5S+Uc9f/8wUWflLiZaNNYXm7QOWTYFLBAroYCcjj9kTC67qDEz9R9Wv8hppJTBmP0tnxFeuwsbb3XHyM4XdA0EDACrA9BESsb2CUgkE+ECxL7y6tv37CvAQX0bv48QlzJv8=
