language: java
sudo: false
jdk:
- oraclejdk8
- oraclejdk9
- openjdk8
before_install:
- chmod +x gradlew
script: "./gradlew junitPlatformTest"
stages:
- test
- coverage
- name: snapshot
  if: branch != master
- name: release
  if: branch = master
jobs:
  include:
  - stage: coverage
    script:
    - "./gradlew check"
    - bash <(curl -s https://codecov.io/bash)
    jdk: oraclejdk8
  - stage: snapshot
    script: "./gradlew artifactoryPublish -Dsnapshot=true -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER"
    jdk: oraclejdk8
  - stage: release
    script: "./gradlew bintrayUpload -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dsigning.pass=$SIGN_PASS -Dbuild.number=$TRAVIS_BUILD_NUMBER"
    jdk: oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/repositories/"
env:
  global:
  - secure: 21esORCUi2A5dfCcbEBA68JpFLWEsnxUbWRy/Jlrm2YMpmYo6gxK//w1uWZSt18mQQKUM9lK1kx+9Bd4BJ0nc3r8uA7d93VdlRG4IN5g+mQoRaQdfq5oMaViWTEMdJKXTfVx/Z0GpwhBfPOGytx9NXq1Fy6Mj7HLKGYlG2B+yLW2zT6BAGnEDj8rkIi5+lL9X3LYihvcLUVIMjswgek9o8zmt6s9piZ3JgMqLm6RIcltp91JPJbKzkL+MBKJEajzRg4tbYNMIRAZgz/7rUsRbrFsPAgP1L9o+a5qBiCbdChPDbJe6mWjTr69Pft15Xv/YoXeWLlnyYlsIylTNVD9Fm5Uxrpe8hpZSXC1G8ErgpdJczKrm9lh4IaRuXWt+kDkLJTXk2rTVoULm1R7FfKBlkfbtoXZIZ47q728O+L2BR4TK80PoqI6fN2RaU5UzrIV25L28kzSPCkHq1EoC8rXHv/4YZU3K455R06Y5MoucEgiYhVmXurrDoYroTwCp8EFsOLjHdF7x4XiYnKiWIbMWipl22zddBLdTmFJeoRtZGBy0tA/S1XKdQsKruzVNd8AyNBWHJTB776aSR0V6ESLHV8pXorZK2Y7C7aqh6XYMO37/Xft8bA7Qe34wNtqqbEIgBrn4qvPegm5rzy7JDXCA+im+tIhTpXkgVn8anperJE=
  - secure: KhTnoxxPBGCOt30UIW3zLck04wPpJ40uV8HZDtUnc94FDazrtYd24jl0XX2qWermgnvzUXkYA3e95NDzv0MMzPJZQGaJI58aDrwUjQGl/W+zcm1/KzsGJjnORdco0xa2Rl6xlTYzKWpGL+M7mpNIf7+WQHC9ih/bK5EmoDE1XJt5sTN9f8tWUg7zwnSejUgQLA8uVr5LEzPecBiDhLLqUKqDgJNrUURDDOxWw2ihX9kVweyDzWa011dcrU7MKt5OuV47+86g2WtMsWotDl5aCKvz9uoo/D5OfF0dAc1MJmEFyrBYKjy+T7DHob59dhDB3bo4jK6kDZxCXsFLr+QudZZ7gPPY9seuzxQxTC/g+I3BLhTQOjTN6GZol+A+hWqb0szaewk3BnOpNYTr/50fYynTyXpfz2Fa+hfLDpMNZy5jTALYjuI3/oZPdQD+GDiLjB3n/LhZgsSzhDriY3ji+N7R78Sr6JVZA/fLJk/28aYQjZkzXgqDcJOMLqFiP3UW6w6BbNJqk7qltL+b1jBDnz29kB717EpJASrg5U1xfFMEt2BhKzYHPv0R9Calo0XSJlokYa2wOOLoha4OPb/dtOfWU9EXg8SnIE9bGEKvPU3EcxQHDNl4ghf0yUP6BynQEo5S0W0w7XVO9YAU8/AT9AMeMUtruU0FBrye12QIvFY=
  - secure: c6xVlsgGyBZ4RvgKVo+Q9C8EG4dZ7vP617HO/zG7ts3S3hmrEYZxKVBlzNmbB7CM3R8irVdHMPC7AhNz8Nrx8Z0LOEfGIRdcdq++MwjcMeu6OnRDdjol1snWLI+Q/reh59dZfU7XWHWjeI54AH40qVKtJBRZ+aoVsVipun+SDufMl6KhYRtuyyST1MYLfqa2f0V2c+d+5B3PscxVGkPpCdR1q4u54PSo0OOZBYty4KShdIIMdU+XcMM4I89KAcdAsumr1ZE2oUjq55TxTi+Ge9H8akPhGo2KN6COWN4OWmtSUgu3utUj9midb66jhcMxSMYhOkYx9CF+7mIxPw/7fVxzc0ZN9PCbuhA0aB9cDjYnEWY+nuEvlFrCM2/S6kUHMnUxMbFIQfxptjSjxu2BvcRyJgFWCKSW0of6YslMm0ZBQyKNJP5NeGYPNAiMCzWFRy38BJ3v/shE4rCTNR1hyolm/lWLraNnJEuR/Zl2/Bcagxu6qCmYQRzJkLmwSxHwJl+xrp5F2I1Q5FE9cCLvOTYwnWptyg//Cv6oKW6fwdMT6/WWr3cZUY7OnyOuIIFHdwIIQE+51XP6Hcv1V0dS1p0igwf3R5elwDQRAW0rwqOoToP5RVpbRK2fkPtJvUM1YG/h2CdsKOWbsv0yfDhFH9uFTvcUtdbv39JEr6DHAJ4=
