language: java
sudo: false
jdk:
- oraclejdk8
- oraclejdk9
- openjdk8
before_install:
- chmod +x gradlew
script: "./gradlew junitPlatformTest"
stages:
- test
- coverage
- name: snapshot
  if: branch != master
- name: release
  if: branch = master
jobs:
  include:
  - stage: coverage
    script:
    - "./gradlew check"
    - bash <(curl -s https://codecov.io/bash)
    jdk: oraclejdk8
  - stage: snapshot
    script: "./gradlew artifactoryPublish -Dsnapshot=true -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER"
    jdk: oraclejdk8
  - stage: release
    script: "./gradlew bintrayUpload -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dsigning.pass=$SIGN_PASS -Dbuild.number=$TRAVIS_BUILD_NUMBER"
    jdk: oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/repositories/"
env:
  global:
  - secure: VDNA0FlkHOoUpOd4E9Cz4F2Ju1xF6B6G5feQVl33siAwhxuu/fvKooyZsKWNpD4kpie8fXRG6ZRntQDKchyQvUABOm7Le30WU0d4f0fSiUKFobJvzqZcLJSikHW4jet7qLdvSspDhWN6JbdeTkNbaT73FVTXi2bilB5k+7zfPNqZN1DNj5lJUPyv/fcDahI03OxkSiH5sUuaYSMu90CyF2K8yTRkhxOBdf4BvxNYphi9vySrk4+Nw/43WFZ7NyInTw5ZW8+Y1Hi+tbe6daIeu44f873f149mDMVcFvdKUQNcGMxMFc83MSEbZZgCMME6WeYPQ6qrrarKRaWXRNeb3ENa6qPTus2Y3/H13FHEemh0VeLKRvvd6qtnZRxQymQEQBm/DowwzJ6T1qC1/aKwU2IDauXA+rL15JRahQTTYPZFAx7nGjNUT9CUcIhl49YpanXnNVUyL0A3aZByHaBp+1rjuXks9/06ygBYWv5WrtML475hArUEpY6T2t8R29ByIK7YRGNQHunrt/BO2Z851k+0RiSNQKnnhVQNgxnQK5X1jb3tO8nEg3Vsn2HfrfDsLFDTlBkmZQKR/myJB3kSNYTOidVeBjWpe26Bw2RPGCT+xt5I0nVlXEnkBnQfBdjKZwvDxDqw1X+BCJRmm0mSpwu5oDRAZih8GIpZHzpqkSM=
  - secure: uCWU3kIzYJxutSjeTCheEGtAiQz0BLbdqo2GXqHknSlnURy7GPn1BxUCOwEL+iRY+7KEVRE/+60ruM89EmVCOQTJIEnFWx4bhGVZ4z+eiHFQ7oRdbh4qeEkhNjJJKo1vyRYQqiIXDZCR5seQO/vP82CyZ/5Z4fUpCv5yFQyDur8Ck7sTdk/W0U/iVvfjlLaA4E7SC+aq/56XEEWtdB5HfZBI9sBnQQC1QYxsgGoNDLFkPKIgkzy+854L6vEvXOkaYm9xFFmAfpLpSmVN4jOPgal6NAPHg92WBOSkaqKW+Rzs8S3Y/aGGppUSBk0nIDZtd7qCkLs38+s444vj/Iou22isDhILG5KOwPuBENxfo1SEEJvEeIbN4FFDYCd8Hz1T0bh/uviEFUH4soyhdvWPXbDk5Zh+jxG4CBDtaxpNJwlEW9Gf2dN1pCihxJE7+nPOBvgMzrBklHVsbuvdMDiS4p3aK9rxO3DRleI46zMh2NvxpNz944uQGHhzW2Ss1TDenFFY6tGRKrz/ZwzqVbei/EhT9P9PyQaUObwL72UqtGvhms1yQkMb3T3jwcrJRPFBUAue5KMqoue+bB4oO90ls5BYfOGb6UVvs2Mpoc5MkwwsEQNVLedJAy5Rxc3BzwjKGNdY82SWb6n7jyaK/i99fpQ7uuWUBX+Q96pJhILEBBQ=
  - secure: p0UTbiZl/IT7YZGZ5sa64tqwnMcKJ4ravf98BJilsEtx6mzdumC6c9oH19bKlgyc1X4kwxr0MWvu8Yw2nWnkmRxLqbUKUdupyT+CBQRRf8gNL44rdMAhg+Yl6Ks3qQL1A6lGgTuO1/3749CMgAkiPt2+XJ8MQmnQcWshSMVBR1gvx55hcjj5QvffTir7pekT1STGEnme/oaPj7cbG6KnFxmCNM7JBz0J47+Vwa6uI9y74pJmiPxfNxfqmw0HYDdOKuUopAmOKVawQET9UTJfpZzg2IgP0F527GE/Y4aMMnv/dd4rLBfUCUA7Yih8URXi2EWO2MIPw+hpp9R4yorHSRc5h9uStiaJIjHRh+pU2ZJmL+39acio4zATpU6uSQ7ZOzlgJ1bwpbEP51x4xe2cia++mcn6+q5AVqiJs6JyrBTiPuBugxfvD2Qk8DxJg+GrbDh9QD4LVNXoRJmPvTZrRec6BbKw4N1CHEuNu/xjftybcKtjsIBQDVvcEj6PuiaA9hkhr95RJK1Au2xd091QEK7XCTPZbp9Ci66XnSgOkMymvbGjNJ8GO0A505ff09qPucqV438+LufZmwT1ZOzY7UaAzKygxc889YRyYIQWXwcqxS29drEGdQBgE3Uqul/R4U2rIjozIjwsAVYEnxLRvI2Joi9Sp2lgrCM/mbVijP0=
